<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Documentation – admetshiny</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-87789dfd1a51b57e76f2f03c6f70bd5e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-c65eef156a02954c7572e454c6e27155.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-87789dfd1a51b57e76f2f03c6f70bd5e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">admetshiny</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../install.html"> 
<span class="menu-text">How to install?</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../publication.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../about.html">
 <span class="dropdown-text">About ADMETShiny</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../espeletia.html">
 <span class="dropdown-text">The flagship specie</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../author.html">
 <span class="dropdown-text">About the author</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-help" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Help</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-help">    
        <li>
    <a class="dropdown-item" href="../feedback.html">
 <span class="dropdown-text">Feedback</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../workflow.html">
 <span class="dropdown-text">Workflows &amp; demostrations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../pages/tutorials.html">
 <span class="dropdown-text">Documentation</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/xavierclementegarcia" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#theory-documentation" id="toc-theory-documentation" class="nav-link active" data-scroll-target="#theory-documentation">Theory &amp; Documentation</a></li>
  <li><a href="#two-working-modules" id="toc-two-working-modules" class="nav-link" data-scroll-target="#two-working-modules">Two working modules</a></li>
  <li><a href="#data-standardization-schema" id="toc-data-standardization-schema" class="nav-link" data-scroll-target="#data-standardization-schema">Data Standardization Schema</a></li>
  <li><a href="#the-mapadmetcolumns-algorithm" id="toc-the-mapadmetcolumns-algorithm" class="nav-link" data-scroll-target="#the-mapadmetcolumns-algorithm">The mapADMETColumns algorithm</a></li>
  <li><a href="#physicochemical-descriptors" id="toc-physicochemical-descriptors" class="nav-link" data-scroll-target="#physicochemical-descriptors">Physicochemical Descriptors</a></li>
  <li><a href="#drug-likeness-filters" id="toc-drug-likeness-filters" class="nav-link" data-scroll-target="#drug-likeness-filters">Drug-Likeness Filters</a></li>
  <li><a href="#boiled-egg-model" id="toc-boiled-egg-model" class="nav-link" data-scroll-target="#boiled-egg-model">BOILED-Egg Model</a></li>
  <li><a href="#p-glycoprotein-substrate-prediction-random-forest-architecture" id="toc-p-glycoprotein-substrate-prediction-random-forest-architecture" class="nav-link" data-scroll-target="#p-glycoprotein-substrate-prediction-random-forest-architecture">P-glycoprotein Substrate Prediction &amp; Random Forest Architecture</a></li>
  <li><a href="#additional-metrics" id="toc-additional-metrics" class="nav-link" data-scroll-target="#additional-metrics">Additional Metrics</a></li>
  <li><a href="#column-mapping-system-admet-master-manager" id="toc-column-mapping-system-admet-master-manager" class="nav-link" data-scroll-target="#column-mapping-system-admet-master-manager">Column Mapping System (ADMET Master Manager)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Documentation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="theory-documentation" class="level3">
<h3 class="anchored" data-anchor-id="theory-documentation">Theory &amp; Documentation</h3>
<p>Admetshiny is an R package that provides an interactive Shiny application and a toolbox of R functions for the management, calculation, filtering, visualization and exploratory analysis of molecular descriptors and ADMET (Absorption, Distribution, Metabolism, Excretion and Toxicity) properties of small molecules.</p>
<p>The package structure is organized into 24 R source files. The NAMESPACE declare 31 exports, the description 10 hard imports and 16 suggest, but we’ve recommended install all the packages with the guide script in the website.</p>
</section>
<section id="two-working-modules" class="level3">
<h3 class="anchored" data-anchor-id="two-working-modules">Two working modules</h3>
<ul>
<li><p><strong>CDK &amp; Webchem:</strong> a four step pipeline where: 1. obtain SMILES via PubChem identifiers, manual entry or CSV upload; 2. Calculate CDK descriptors; 3. apply drug-likeness filters; 4. visualize the results.</p></li>
<li><p><strong>ADMET Master Manager:</strong> a four step wizard: 1. Upload &amp; Preview; 2. Map Columns; 3. Filter; 4. Plots</p></li>
</ul>
<p>Both modules feed their final filtered dataset into the shared Report tab, which uses rmarkdown to render a comprehensive analysis document in HTML, PDF or Word format.</p>
</section>
<section id="data-standardization-schema" class="level3">
<h3 class="anchored" data-anchor-id="data-standardization-schema">Data Standardization Schema</h3>
<p>The application uses a single canonical column schema regardless of the original data source.</p>
<table class="caption-top table">
<caption>The standardization column names</caption>
<thead>
<tr class="header">
<th>Field code</th>
<th>Standard column name</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SMILES</td>
<td>CanonicalSMILES</td>
<td><code>string</code></td>
</tr>
<tr class="even">
<td>Name</td>
<td>Name</td>
<td><code>string</code></td>
</tr>
<tr class="odd">
<td>LogP</td>
<td>LogP</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>WLOGP</td>
<td>WLOGP</td>
<td><code>numeric</code></td>
</tr>
<tr class="odd">
<td>TPSA</td>
<td>TPSA</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>HBD</td>
<td>#H-bond donors</td>
<td><code>numeric</code></td>
</tr>
<tr class="odd">
<td>HBA</td>
<td>#H bond acceptors</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>Rotatable Bonds</td>
<td>#Rotatable bonds</td>
<td><code>numeric</code></td>
</tr>
<tr class="odd">
<td>Molar Refractivity</td>
<td>MR</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>Heavy Atoms</td>
<td>#Heavy atoms</td>
<td><code>numeric</code></td>
</tr>
<tr class="odd">
<td>Aromatic Heavy Atoms</td>
<td>#Aromatic heavy atoms</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>GI Absorption</td>
<td>GI absorption</td>
<td><code>categorical</code></td>
</tr>
<tr class="odd">
<td>Gi Absorption_num</td>
<td>GI_absorption_num</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>BBB Permeant</td>
<td>BBB permeant</td>
<td><code>categorical</code></td>
</tr>
<tr class="odd">
<td>BBB Permeant_num</td>
<td>BBB_num</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>Pgp Substrate</td>
<td>Pgp substrate</td>
<td><code>categorical</code></td>
</tr>
<tr class="odd">
<td>Pgp Substrate_num</td>
<td>Pgp_num</td>
<td><code>numeric</code></td>
</tr>
<tr class="even">
<td>LogS</td>
<td>LogS</td>
<td><code>numeric</code></td>
</tr>
<tr class="odd">
<td>LogD</td>
<td>LogD</td>
<td><code>numeric</code></td>
</tr>
</tbody>
</table>
</section>
<section id="the-mapadmetcolumns-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="the-mapadmetcolumns-algorithm">The mapADMETColumns algorithm</h3>
<p>The function executes seven sequential steps:</p>
<ol type="1">
<li><p><strong>Rename columns:</strong> For each user column pair in the mapping, the field code is looked up in code to standard. If a target name already exists and points to a different column, the old column is dropped first to prevent duplicated name confusion.</p></li>
<li><p><strong>Numeric coercion:</strong> The standard numeric columns (<code>MW, LogP, WLOGP, TPSA, HBD, HBA, RB, MR, heavy atoms, aromatics atoms, LogS, LogD, GI_absorption_num, BBB_num_Pgp_num</code>) are coerced with suppress warnings.</p></li>
<li><p><strong>ADMET numeric to categorical conversion:</strong> If the user supplied a numeric column mapped to GI Absorption and another, the corresponding categorical column is derived using a threshold of 0.5</p></li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"GI_absorption_num"</span> <span class="sc">%in%</span> <span class="fu">names</span>(data)) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a> v <span class="ot">&lt;-</span> data<span class="sc">$</span>GI_absorption_num</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a> data[[<span class="st">"GI absorption"</span>]] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">is.na</span>(v), <span class="cn">NA</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">ifelse</span>(v <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="st">"High"</span>, <span class="st">"Low"</span>))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a> data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ol start="4" type="1">
<li><strong>Optional CDK calculation for missing descriptors:</strong> When the function <code>calculate_cdk = TRUE</code>, and a CanonicalSMILES column exists, the function computes the set of missing standard descriptors via <code>setdiff()</code>, MAPS each to its CDK short code. <strong>For more information about to this function, you could read the technical documentation.</strong></li>
<li><strong>WLOGP/LogP precedence logic:</strong> WLOGP is the BOILED-Egg’s original calibration axis <span class="citation" data-cites="daina2016a">(<a href="#ref-daina2016a" role="doc-biblioref">Daina and Zoete 2016a</a>)</span>. When the user has explicitly mapped a column to WLOGP but has not mapped another column to LogP, the generic LogP column is silently set to the WLOGP values:</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ----- 5. If WLOGP present and LogP not mapped, set LogP = WLOGP -----</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="do">## WLOGP is preferred for BOILED-Egg (official calibration), but only</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="do">## if the user didn't explicitly map a different column to LogP.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"WLOGP"</span> <span class="sc">%in%</span> <span class="fu">names</span>(data) <span class="sc">&amp;&amp;</span> <span class="sc">!</span><span class="st">"LogP"</span> <span class="sc">%in%</span> <span class="fu">names</span>(data)) {</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a> data<span class="sc">$</span>LogP <span class="ot">&lt;-</span> data<span class="sc">$</span>WLOGP</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>History note. An earlier version of this <span class="fu">step</span> (Issue <span class="dv">7</span> <span class="cf">in</span> worklog.md) used the simpler condition <span class="st">"WLOGP"</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="sc">%in%</span> <span class="fu">names</span>(data) and silently overwrote a user<span class="sc">-</span>mapped LogP column. The current guarded condition</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>respects an explicit LogP mapping.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ol start="6" type="1">
<li><strong>Compute violation columns:</strong> The standardized data is passed through <code>computeViolationColumns()</code> to add the five “#Violations” columns used by the filters.</li>
<li>Compute ADMET properties: If any of GI absorption, BBB permeant or Pgp substrate is missing, <code>computeADMETProperties()</code> is called. To honour user-provided categorical columns, the function temporarily stashes any pre-existing categorical ADMET column runs <code>computeADMETProperties()</code>, then restores the stashed values.</li>
</ol>
</section>
<section id="physicochemical-descriptors" class="level3">
<h3 class="anchored" data-anchor-id="physicochemical-descriptors">Physicochemical Descriptors</h3>
<section id="molecular-weight-mw" class="level4">
<h4 class="anchored" data-anchor-id="molecular-weight-mw">Molecular Weight (MW)</h4>
<p>The molecular weight is the sum of the atomic weights of every atom in the molecule, weighted by the count of each atom type:</p>
<p><span class="math display">\[\mathrm{MW} \;=\; \sum_{i=1}^{N} A_i \times \mathrm{MW}_i,\]</span></p>
<p>That’s equation define the next functions, where <strong>N</strong> is the number of distinct atom types <strong>Ai</strong> is the count of atoms of type and <strong>MWi</strong> is the monoisotopic or average atomic weight of atom type taken from the IUPAC standard atomic weights <span class="citation" data-cites="roskoski2020">(<a href="#ref-roskoski2020" role="doc-biblioref">Roskoski 2020</a>)</span>.</p>
</section>
<section id="logp-lipophilicity" class="level4">
<h4 class="anchored" data-anchor-id="logp-lipophilicity">LogP (Lipophilicity)</h4>
<p>The partition coefficient <strong>LogP</strong> between <strong>n-octanol</strong> and water is estimated by several independent methods. ADMETShiny exposes the two atomistic fragmental predictors <strong>ALogP</strong> and <strong>WLOGP</strong>, together with <strong>Consensus LogP</strong> that aggregates five distinct methods <span class="citation" data-cites="filimonov2014">(<a href="#ref-filimonov2014" role="doc-biblioref">Filimonov et al. 2014</a>)</span>.</p>
<p>At the case to <strong>ALogP</strong> , is calculated with <strong>Development Kit (CDK)</strong>, that’s implementation of uses an atomistic fragmental method: every atom is assigned to a typed fragment whose contribution has been regression fitted on a curated training set. The <strong>LogP</strong> is the sum of fragment contributions:</p>
<p><span class="math display">\[ \mathrm{LogP} \;=\; \sum_{i=1}^{N} f_i \times n_i,\]</span></p>
</section>
<section id="topological-polar-surface-area-tpsa" class="level4">
<h4 class="anchored" data-anchor-id="topological-polar-surface-area-tpsa">Topological Polar Surface Area (TPSA)</h4>
<p>The <strong>TPSA</strong> is computed by <em>Ertl’s</em> fragment based method as the sum of polar atom type surface contributions over 43 predefined atom types:</p>
<p><span class="math display">\[\mathrm{WLOGP} \;=\; \sum_{i=1}^{N} f_i \times n_i,\]</span></p>
<p>where the count of polar atom type is defined by elements, hybridization, and number of attached hydrogens.</p>
</section>
<section id="molar-refractivity-mr" class="level4">
<h4 class="anchored" data-anchor-id="molar-refractivity-mr">Molar Refractivity (MR)</h4>
<p>Molar refractivity is related to the refractive index <em>n</em>, the molecular weight <em>MW</em>, and the density <em>d</em> of the pure compound by the Lorenz-Lorentz equation:</p>
<p><span class="math display">\[\mathrm{MR} \;=\; \frac{n^2 - 1}{n^2 + 2} \times \frac{\mathrm{MW}}{d}\]</span></p>
<p>Because the refractive index and density are not generally available for arbitrary molecules, ADMETShiny uses the Wildman-Crippen fragmental estimator:</p>
<p><span class="math display">\[\mathrm{MR} \;=\; \sum_{i=1}^{N} r_i \times n_i,\]</span></p>
</section>
<section id="hydrogen-bond-donors-hbd" class="level4">
<h4 class="anchored" data-anchor-id="hydrogen-bond-donors-hbd">Hydrogen Bond Donors (HBD)</h4>
<p>The HBD count is the number of N-H and O-H bonds in the molecule, that’s the total number hydrogens bound to a nitrogen or oxygen atom.</p>
<p><span class="math display">\[\mathrm{HBD} \;=\; \sum_{i} (\text{atom}_i \in \{\mathrm{N}, \mathrm{O}\}) \times h_i,\]</span></p>
</section>
<section id="hydrogen-bond-acceptors-hba" class="level4">
<h4 class="anchored" data-anchor-id="hydrogen-bond-acceptors-hba">Hydrogen Bond Acceptors (HBA)</h4>
<p>The HBA count is the number of nitrogen and oxygen atoms in the molecule with Lipinski’s definition.</p>
<p><span class="math display">\[\mathrm{HBA} \;=\; \sum_{i} (\text{atom}_i \in \{\mathrm{N}, \mathrm{O}\}).\]</span></p>
</section>
<section id="rotatable-bonds-rb" class="level4">
<h4 class="anchored" data-anchor-id="rotatable-bonds-rb">Rotatable Bonds (RB)</h4>
<p>A rotatable bond is any single non-ring non-terminal bond between two non-hydrogen atoms:</p>
<p><span class="math display">\[\mathrm{RB} = \sum_{(i,j)\in E} \mathbb{I}(b_{ij} = 1) \cdot \mathbb{I}(\text{ring}_{ij} = 0) \cdot \mathbb{I}(\deg(i) &gt; 1) \cdot \mathbb{I}(\deg(j) &gt; 1)\]</span></p>
</section>
<section id="heavy-atoms-and-aromatic-heavy-atoms" class="level4">
<h4 class="anchored" data-anchor-id="heavy-atoms-and-aromatic-heavy-atoms">Heavy Atoms and Aromatic Heavy Atoms</h4>
<p>The heavy-atom count is the total number of non-hydrogen atoms:</p>
<p><span class="math display">\[\mathrm{HA} = \sum_{i} \mathbb{I}(\text{atom}_i \neq \mathrm{H})\]</span></p>
<p>The heavy-atom count is the total number of non-hydrogen atoms. The aromatic heavy-atom count is the subset of heavy atoms that belong to an aromatic ring:</p>
</section>
</section>
<section id="drug-likeness-filters" class="level3">
<h3 class="anchored" data-anchor-id="drug-likeness-filters">Drug-Likeness Filters</h3>
<p>Each drug-likeness filter is formalized as an indicator function combination. For each rule we define a violation indicator. <em>V=0</em> denotes as compound that satisfies the rule, <em>V=1</em> a violation.</p>
<section id="lipinski-rule-of-five" class="level4">
<h4 class="anchored" data-anchor-id="lipinski-rule-of-five">Lipinski Rule of Five</h4>
<p>The Lipinski violation count is the number of threshold superations over the four canonical physicochemical properties:</p>
<p><span class="math display">\[V_{\mathrm{Lipinski}} = \mathbb{I}(\mathrm{MW} &gt; 500) + \mathbb{I}(\mathrm{LogP} &gt; 5) + \mathbb{I}(\mathrm{HBA} &gt; 10) + \mathbb{I}(\mathrm{HBD} &gt; 5)\]</span></p>
<p>A compound is considered drug-like when Vlipinski = 0. A single violation (V=1) is still considered acceptable, following Lipinski’s original “one violation allowed” convention.</p>
</section>
<section id="veber-filter" class="level4">
<h4 class="anchored" data-anchor-id="veber-filter">Veber Filter</h4>
<p>The Veber rule predicts good oral bioavailability from molecular flexibility and polarity. The original Veber criterion uses only RB &gt; 10 and TPSA &gt; 140 branches; ADMETShiny additionally requires the H-bond pair count to exceed 12 in the TPSA based branch, matching the form used by SwissADME <span class="citation" data-cites="daina2017">(<a href="#ref-daina2017" role="doc-biblioref">Daina et al. 2017</a>)</span>.</p>
<p><span class="math display">\[V_{\mathrm{Veber}} = \Ind\Bigl(\mathrm{RB} &gt; 10 \lor \bigl(\mathrm{TPSA} &gt; 140 \land (\mathrm{HBA} + \mathrm{HBD}) &gt; 12\bigr)\Bigr)\]</span></p>
</section>
<section id="ghose-filter" class="level4">
<h4 class="anchored" data-anchor-id="ghose-filter">Ghose Filter</h4>
<p>The Ghose filter defines a drug-like chemical space by four simultaneous range constraints:</p>
<p><span class="math display">\[\begin{aligned}
V_{\mathrm{Ghose}} = {} &amp; \mathbf{1}(\mathrm{MW} &lt; 160 \lor \mathrm{MW} &gt; 480) \\
                        &amp; + \mathbf{1}(\mathrm{MR} &lt; 40 \lor \mathrm{MR} &gt; 130) \\
                        &amp; + \mathbf{1}(\mathrm{LogP} &lt; -0.4 \lor \mathrm{LogP} &gt; 5.6) \\
                        &amp; + \mathbf{1}(\mathrm{HA} &lt; 20 \lor \mathrm{HA} &gt; 70)
\end{aligned}\]</span></p>
<p>Each of the four properties must lie inside its permissible range for a compound to satisfy the rule.</p>
</section>
<section id="egan-filter" class="level4">
<h4 class="anchored" data-anchor-id="egan-filter">Egan Filter</h4>
<p>The Egan filter predicts oral absorption from lipophilicity and polarity alone:</p>
<p><span class="math display">\[V_{\mathrm{Egan}} = \mathbb{I}(\mathrm{TPSA} &gt; 131.6) + \mathbb{I}(\mathrm{LogP} &gt; 5.88)\]</span></p>
<p>A compound satisfies the Egan rule when both indicators are zero.</p>
</section>
<section id="muegge-filter" class="level4">
<h4 class="anchored" data-anchor-id="muegge-filter">Muegge Filter</h4>
<p>The Muegge “Lead-like” filter adds a pharmacophore points constraint <strong>PP = HBA + HBD.</strong></p>
<p><span class="math display">\[\def\Ind{\operatorname{Ind}}
\begin{aligned}
V_{\mathrm{Muegge}} = {} &amp; \Ind(\mathrm{MW} &lt; 200 \lor \mathrm{MW} &gt; 600) \\
                         &amp; + \Ind(\mathrm{LogP} &lt; -2 \lor \mathrm{LogP} &gt; 5) \\
                         &amp; + \Ind(\mathrm{HBA} &gt; 10) \\
                         &amp; + \Ind(\mathrm{HBD} &gt; 5) \\
                         &amp; + \Ind(\mathrm{RB} &gt; 15) \\
                         &amp; + \Ind(\mathrm{TPSA} &gt; 150) \\
                         &amp; + \Ind(\mathrm{PP} &lt; 4)
\end{aligned}\]</span></p>
<p>The last term enforces the presence of at least four pharmacophore points H-bond donor or acceptor atoms, excluding molecules that lack the minimal polar functionality required for specific target recognition.</p>
</section>
</section>
<section id="boiled-egg-model" class="level3">
<h3 class="anchored" data-anchor-id="boiled-egg-model">BOILED-Egg Model</h3>
<p>The BOILED-Egg model classifies small molecules for two ADME endpoints human intestinal absorption (HIA) and blood-brain barrier (BBB) permeation from physicochemical descriptors only: <span class="math display">\[TPSA\]</span> on the x-axis and <span class="math display">\[LogP\]</span> on the y-axis.</p>
<p>A molecule whose point <span class="math display">\[(x,y) = (TPSA, LogP) \]</span> lies inside the HIA ellipse is predicted to be passively absorbed by the gastrointestinal tract; a molecule inside the BBB ellipse “yolk” is predicted to cross the blood-brain barrier.</p>
<section id="official-wlogp-polygons" class="level4">
<h4 class="anchored" data-anchor-id="official-wlogp-polygons">Official WLOGP Polygons</h4>
<p>Each ellipse is fully defined by scalar parameters: the two focus points <span class="math display">\[ F_1 = (x_1,y_1)\]</span> and <span class="math display">\[ F_2 = (x_2, y_2) \]</span> and the major axis length. A point <span class="math display">\[ P= (x,y)\]</span> lies inside the ellipse if and only if the sum of its distances to the two points does not exceed d:</p>
<p><span class="math display">\[d(P, F_1) + d(P, F_2) \;\leq\; d,\]</span></p>
<p>where the Euclidean point to focus distances are:</p>
<p><span class="math display">\[\begin{aligned}
d(P, F_1) &amp;= \sqrt{(x - x_1)^2 + (y - y_1)^2} \\
d(P, F_2) &amp;= \sqrt{(x - x_2)^2 + (y - y_2)^2}
\end{aligned}\]</span> {#eq-distancias}</p>
<p>The constants defining the official WLOGP ellipses for HIA+ and BBB+ are calibrated on the SwissADME training set <span class="citation" data-cites="daina2016 daina2017">(<a href="#ref-daina2016" role="doc-biblioref">Daina and Zoete 2016b</a>; <a href="#ref-daina2017" role="doc-biblioref">Daina et al. 2017</a>)</span>. We had use this when WLOGP are available for ADMETShiny.</p>
</section>
<section id="point-in-polygon-test-approximation" class="level4">
<h4 class="anchored" data-anchor-id="point-in-polygon-test-approximation">Point in Polygon Test approximation</h4>
<p>For runtime classification, the analytical ellipse is discrete into a closed polygon of <em>n</em> boundary points. The query point <em>P</em> is then decided by the ray-casting algorithm as a horizontal ray is cast from <em>P</em> in the +x direction axis, and the number of polygon edges crossed by the ray is counted. The parity of the count gives the classification:</p>
<p><span class="math display">\[\mathrm{inside}(P) = \left( \sum_{e \in E_{\mathrm{poly}}} \mathbb{I}(\text{ray crosses } e) \right) \bmod 2,\]</span></p>
<p>That definition in the practice in ADMETShiny delegate this test to <code>sp::point.in.polygon()</code> when available, with the ray-casting formulation above as a pure R fallback.</p>
</section>
<section id="logp-source-selection-and-trained-ellipses" class="level4">
<h4 class="anchored" data-anchor-id="logp-source-selection-and-trained-ellipses">LogP Source selection and trained ellipses</h4>
<p>Because the official ellipses were calibrated against WLOGP, their application to data produced with a different LogP estimator can produce systematic misclassification. ADMETShiny therefore selects the polygon set as a function of the user-supplied LogP source:</p>
<p><span id="eq-be-sel"><span class="math display">\[\mathrm{polygons} =
\begin{cases}
\text{WLOGP official} &amp; \text{if } \texttt{logp\_source} = \text{"WLOGP"}, \\
\text{ALogP-trained}  &amp; \text{otherwise}.
\end{cases} \tag{1}\]</span></span></p>
<p>When the input data contain ALogP but no WLOGP, ADMETShiny uses ALogP trained polygons. These polygons are re-derived by ADMETShiny following the Monte-Carlo optimization protocol using a CDK training set of 439 molecules <span class="citation" data-cites="daina2016">(<a href="#ref-daina2016" role="doc-biblioref">Daina and Zoete 2016b</a>)</span>.</p>
</section>
<section id="monte-carlo-optimization" class="level4">
<h4 class="anchored" data-anchor-id="monte-carlo-optimization">Monte-Carlo optimization</h4>
<p>We have considered the Daina &amp; Zoete methodology for this optimization. This is performed in the normalized <em>(TPSA, ALogP)</em> space. Normalization uses the empirical mean and standard deviation of the training set.</p>
<p><span class="math display">\[\begin{aligned}
x' &amp;= \frac{x - \mu_x}{\sigma_x} &amp; y' &amp;= \frac{y - \mu_y}{\sigma_y}
\end{aligned}\]</span></p>
<p>Each ellipse is parameterized by a five-dimensional vectors. The optimization maximizes a regularized with Matthews Correlation Coefficient:</p>
<p><span class="math display">\[\mathrm{Score} = \mathrm{MCC} - 0.05 \times S\]</span> The MCC itself is the standard balanced classification metric,</p>
<p><span id="eq-mcc-definition"><span class="math display">\[\mathrm{MCC} = \frac{\mathrm{TP} \times \mathrm{TN} - \mathrm{FP} \times \mathrm{FN}}{\sqrt{(\mathrm{TP}+\mathrm{FP})(\mathrm{TP}+\mathrm{FN})(\mathrm{TN}+\mathrm{FP})(\mathrm{TN}+\mathrm{FN})}} \tag{2}\]</span></span></p>
</section>
<section id="validation-data-and-accuracy" class="level4">
<h4 class="anchored" data-anchor-id="validation-data-and-accuracy">Validation data and accuracy</h4>
<p>The re-trained ALogP ellipses were validated against the CDK training set of 439 molecules. The classification performance is summarized in the next table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Model</th>
<th style="text-align: center;">MCC</th>
<th style="text-align: center;">Accuracy</th>
<th style="text-align: center;">TP</th>
<th style="text-align: center;">FN</th>
<th style="text-align: center;">FP</th>
<th style="text-align: center;">TN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">HIA</td>
<td style="text-align: center;">0.986</td>
<td style="text-align: center;">99.5%</td>
<td style="text-align: center;">348</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">89</td>
</tr>
<tr class="even">
<td style="text-align: center;">BBB</td>
<td style="text-align: center;">0.977</td>
<td style="text-align: center;">98.9%</td>
<td style="text-align: center;">230</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">204</td>
</tr>
</tbody>
</table>
<p>The HIA ellipse correctly classifies 348 of 350 absorbed molecules and all 89 non absorbed molecules. The BBB ellipse correctly classifies 230 of 235 permeant molecules and all 204 non permeant molecules. Both ellipses achieve zero false positives, which is desirable for a screening tool where over prediction of absorption &amp; permeation would generate costly false leads.</p>
</section>
</section>
<section id="p-glycoprotein-substrate-prediction-random-forest-architecture" class="level3">
<h3 class="anchored" data-anchor-id="p-glycoprotein-substrate-prediction-random-forest-architecture">P-glycoprotein Substrate Prediction &amp; Random Forest Architecture</h3>
<p>P-glycoprotein (P-gp, ABCB1) substrate status is predicted by a Random Forest of <em>K= 100</em> binary decision trees. Each tree is trained independently on a bootstrap sample of the training set; at each internal node, the split is chosen over a random subset of features. Each leaf node stores the fraction of training set samples in that leaf that are P-gp substrates:</p>
<p><span id="eq-leaf-probability-expanded"><span class="math display">\[P(\mathbf{x}) = \dfrac{\#\{\text{substrates in leaf reached by } \mathbf{x}\}}{\#\{\text{samples in leaf reached by } \mathbf{x}\}} \tag{3}\]</span></span></p>
<p>The final binary classification applies a threshold of 0.5 to the averaged probability:</p>
<p><span id="eq-pgp-classify"><span class="math display">\[\text{P-gp substrate} =
\begin{cases}
\text{"Yes"} &amp; \text{if } P(\text{substrate} \mid \mathbf{x}) \ge 0.5, \\
\text{"No"}  &amp; \text{otherwise}.
\end{cases} \tag{4}\]</span></span></p>
<section id="training-data-methodology-model-performance" class="level4">
<h4 class="anchored" data-anchor-id="training-data-methodology-model-performance">Training Data, methodology &amp; model performance</h4>
<p>The model was trained on 882 experimental P-gp (ABCB1) compounds extracted from Metrabase. The class distribution is 474 substrates (positive class) and 408 non-substrates (negative class). The nine physicochemical descriptors of equation are used as features. Their means and standard deviations in the training set are listed in the next table.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Descriptor</th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">MW</td>
<td style="text-align: center;">426.05</td>
<td style="text-align: center;">168.47</td>
</tr>
<tr class="even">
<td style="text-align: center;">LogP</td>
<td style="text-align: center;">3.28</td>
<td style="text-align: center;">2.22</td>
</tr>
<tr class="odd">
<td style="text-align: center;">TPSA</td>
<td style="text-align: center;">89.63</td>
<td style="text-align: center;">59.68</td>
</tr>
<tr class="even">
<td style="text-align: center;">HBD</td>
<td style="text-align: center;">1.91</td>
<td style="text-align: center;">1.83</td>
</tr>
<tr class="odd">
<td style="text-align: center;">HBA</td>
<td style="text-align: center;">5.71</td>
<td style="text-align: center;">3.65</td>
</tr>
<tr class="even">
<td style="text-align: center;">RB</td>
<td style="text-align: center;">5.72</td>
<td style="text-align: center;">4.54</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Heavy Atoms</td>
<td style="text-align: center;">30.28</td>
<td style="text-align: center;">12.06</td>
</tr>
<tr class="even">
<td style="text-align: center;">Aromatic Atoms</td>
<td style="text-align: center;">11.17</td>
<td style="text-align: center;">7.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">MR</td>
<td style="text-align: center;">115.31</td>
<td style="text-align: center;">43.87</td>
</tr>
</tbody>
</table>
<p>The model performance was evaluated by five fold stratified cross validation.</p>
<table class="caption-top table">
<caption>P-gp substrate prediction: 5-fold stratified cross validation performance</caption>
<thead>
<tr class="header">
<th>Metric</th>
<th>Random Forest</th>
<th>SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td>0.694</td>
<td>0.025</td>
</tr>
<tr class="even">
<td>MCC</td>
<td>0.383</td>
<td>0.050</td>
</tr>
<tr class="odd">
<td>Sensitivity</td>
<td>0.700</td>
<td>-</td>
</tr>
<tr class="even">
<td>Specificity</td>
<td>0.591</td>
<td>-</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="additional-metrics" class="level3">
<h3 class="anchored" data-anchor-id="additional-metrics">Additional Metrics</h3>
<section id="composite-drug-likeness-score" class="level4">
<h4 class="anchored" data-anchor-id="composite-drug-likeness-score">Composite Drug-Likeness Score</h4>
<p>ADMETShiny combines the available drug-likeness filters into a single composite score. For a compound evaluated against <em>n</em> rules, the score is the percentage of rules with zero violations:</p>
<p><span id="eq-compliance-score"><span class="math display">\[\mathrm{Score} = \frac{1}{n_{\mathrm{rules}}} \sum_{i=1}^{n_{\mathrm{rules}}} \mathbf{1}(V_i = 0) \times 100 \tag{5}\]</span></span></p>
<p>The score is discreted into three bands:</p>
<ul>
<li><strong>Excellent</strong> — <span class="math inline">\(\mathrm{Score} \ge 80\)</span>.</li>
<li><strong>Acceptable</strong> — <span class="math inline">\(60 \le \mathrm{Score} &lt; 80\)</span>.</li>
<li><strong>Poor</strong> — <span class="math inline">\(\mathrm{Score} &lt; 60\)</span>.</li>
</ul>
</section>
</section>
<section id="column-mapping-system-admet-master-manager" class="level3">
<h3 class="anchored" data-anchor-id="column-mapping-system-admet-master-manager">Column Mapping System (ADMET Master Manager)</h3>
<p>The ADMET Master module accepts arbitrary CSV or Excel inputs whose columns names may differ from the canonical ADMETShiny schema. The function <code>mapADMETColumns</code> takes a user supplied mapping vector <strong>m</strong> that maps each canonical name to the corresponding source column name, and applies a deterministic column rename:</p>
<p><span id="eq-data-normalization"><span class="math display">\[\mathrm{data}_{\mathrm{standard}} = \operatorname{rename}(\mathrm{data}_{\mathrm{raw}}, \mathbf{m}) \tag{6}\]</span></span></p>
<p>After column mapping, ADMET Master converts numerical endpoint predictions into the categorical labels used by the visualization modules. For the HIA endpoint, the conversion is:</p>
<p><span id="eq-map-hia"><span class="math display">\[\text{GI absorption} =
\begin{cases}
\text{"High"} &amp; \text{if } p_{\mathrm{HIA}} \ge 0.5, \\
\text{"Low"}  &amp; \text{if } p_{\mathrm{HIA}} &lt; 0.5.
\end{cases} \tag{7}\]</span></span></p>
<section id="references" class="level4">




</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-daina2017" class="csl-entry" role="listitem">
Daina, Antoine, Olivier Michielin, and Vincent Zoete. 2017. <span>“SwissADME: A Free Web Tool to Evaluate Pharmacokinetics, Drug-Likeness and Medicinal Chemistry Friendliness of Small Molecules.”</span> <em>Scientific Reports</em> 7 (1): 42717. <a href="https://doi.org/10.1038/srep42717">https://doi.org/10.1038/srep42717</a>.
</div>
<div id="ref-daina2016" class="csl-entry" role="listitem">
Daina, Antoine, and Vincent Zoete. 2016b. <span>“A BOILED<span>-</span>Egg to Predict Gastrointestinal Absorption and Brain Penetration of Small Molecules.”</span> <em>Chemmedchem</em> 11 (11): 1117–21. <a href="https://doi.org/10.1002/cmdc.201600182">https://doi.org/10.1002/cmdc.201600182</a>.
</div>
<div id="ref-daina2016a" class="csl-entry" role="listitem">
Daina, Antoine, and Vincent Zoete. 2016a. <span>“A BOILED<span>-</span>Egg to Predict Gastrointestinal Absorption and Brain Penetration of Small Molecules.”</span> <em>Chemmedchem</em> 11 (11): 1117–21. <a href="https://doi.org/10.1002/cmdc.201600182">https://doi.org/10.1002/cmdc.201600182</a>.
</div>
<div id="ref-filimonov2014" class="csl-entry" role="listitem">
Filimonov, D. A., A. A. Lagunin, T. A. Gloriozova, et al. 2014. <span>“Prediction of the Biological Activity Spectra of Organic Compounds Using the Pass Online Web Resource.”</span> <em>Chemistry of Heterocyclic Compounds</em> 50 (3): 444–57. <a href="https://doi.org/10.1007/s10593-014-1496-1">https://doi.org/10.1007/s10593-014-1496-1</a>.
</div>
<div id="ref-roskoski2020" class="csl-entry" role="listitem">
Roskoski, Robert. 2020. <span>“Properties of FDA-Approved Small Molecule Protein Kinase Inhibitors: A 2020 Update.”</span> <em>Pharmacological Research</em> 152 (February): 104609. <a href="https://doi.org/10.1016/j.phrs.2019.104609">https://doi.org/10.1016/j.phrs.2019.104609</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/xavierclementegarcia\.github\.io\/ADMETShiny\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MIT license, 2026 - ADMETShiny</p>
</div>   
    <div class="nav-footer-center">
<p>Made with <a href="https://www.r-project.org/"><img src="https://www.r-project.org/Rlogo.png" alt="R" width="25px"></a> and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" alt="Quarto" width="65px"></a>.</p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/xavierclementegarcia">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>