project:
  type: website
  output-dir: docs 
resources: 
  - google02a8a0c3d0dab92d.html

website:
  title: "admetshiny"
  site-url: https://xavierclementegarcia.github.io/ADMETShiny/
  description: >
    ADMETShiny is an open-source R/Shiny platform for ADMET prediction,
    cheminformatics, molecular descriptor calculation, QSAR analysis,
    and computational drug discovery.
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: install.qmd
      - href: workflow.qmd
      - href: espeletia.qmd
      - href: publication.qmd
      
    right:
      - text: Features
        menu:
          - href: tutorials.qmd
          - href: book.qmd
          - href: author.qmd 

    tools:
      - href: https://github.com/xavierclementegarcia
        icon: github
          

        

format:
  html:
    theme:
      light: 
        - vapor 
        - styles.scss
      dark: 
        - vapor
        - styles.scss
    css: styles.css
    toc: true
        

editor: visual

