project:
  type: website
  output-dir: docs 
resources: 
  - google02a8a0c3d0dab92d.html

website:
  title: "admetshiny"
  site-url: https://xavierclementegarcia.github.io/ADMETShiny/
  description: >
    ADMETShiny is an open-source R/Shiny platform for ADMET prediction,
    cheminformatics, molecular descriptor calculation, QSAR analysis,
    and computational drug discovery.
  reader-mode: true
  back-to-top-navigation: true
  page-footer: 
    left: 
      "MIT license, 2026 - ADMETShiny"
    right: 
      - icon: github
        href: https://github.com/xavierclementegarcia

    center: |
      Made with <a href="https://www.r-project.org/"><img src="https://www.r-project.org/Rlogo.png" alt="R" width="25px"></a> 
      and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" alt="Quarto" width="65px"></a>.
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: install.qmd
      - href: publication.qmd
        
      - text: About
        menu:
          - href: about.qmd
          - href: espeletia.qmd
          - href: author.qmd 
    right:
      - text: Help
        menu:
          - href: feedback.qmd
          - href: workflow.qmd
          - href: pages\tutorials.qmd


    tools:
      - href: https://github.com/xavierclementegarcia
        icon: github
          

        

format:
  html:
    theme:
      light: 
        - pulse 
        - styles.scss
      dark: 
        - vapor
        - styles.scss
    css: styles.css
    toc: true
        

editor: visual
